import type { TranslationKeys } from "./es";

export const en: TranslationKeys = {
  hero: {
    title: "Calculate how much a vulnerability or poor code quality could cost your company",
    subtitle: "Convert technical risks into financial impact.",
    ctaPrimary: "Calculate my risk",
    ctaSecondary: "Request technical assessment",
    trust: "Based on ISO/IEC 25010 quality models, OWASP Top 10, OWASP Mobile Top 10 and industry risk criteria.",
  },
  disclaimer:
    "Results generated by this tool are indicative estimates based on user-provided information, common risk factors and reference models. They do not constitute a formal audit, certification, legal opinion or forensic analysis.",
};